#   _  __                   _ _ ____             _             
#  | |/ /__ ___      ____ _(_|_)  _ \ __ _ _ __ | |_ ___ _   _ 
#  | ' // _` \ \ /\ / / _` | | | |_) / _` | '_ \| __/ __| | | |
#  | . \ (_| |\ V  V / (_| | | |  __/ (_| | | | | |_\__ \ |_| |
#  |_|\_\__,_| \_/\_/ \__,_|_|_|_|   \__,_|_| |_|\__|___/\__,_|
#                   ____  _             _                 _        
#  [   ANSIBLE   ] |  _ \| | __ _ _   _| |__   ___   ___ | | _____ 
#  Please only use | |_) | |/ _` | | | | '_ \ / _ \ / _ \| |/ / __|
#  playbooks if    |  __/| | (_| | |_| | |_) | (_) | (_) |   <\__ \
#  you know what   |_|   |_|\__,_|\__, |_.__/ \___/ \___/|_|\_\___/
#  they change/do                 |___/ 
# 
#  .---------| Debian "Kawaiipantsu custom" Harden SSHd config
#  |
#  | This is a special playbook that uses my special custom sshd
#  | harden sshd_config file. This should work in most cases and
#  | for production usage, all commented and easy to follow.
#  |
#  | Taking it directly from GIST, so single point to keep updated
#  |
#  | Also i have kept sftp subsystem, but would had like to
#  | disable it as well but ansible is using it in many cases ...
#  |
#  | PS: This will add a pre-auth default message as well!!
#  |     Change afterwards if you dont want the default...
#  `---------------------------------------------------------------
---

- hosts: debian
  tasks:
    - name: Get timestamp for bak files
      ansible.builtin.set_fact:
        bak_ts: "{{ lookup('pipe', 'date +%Y%m%dT%H%M%S') }}"
        
    - name: Make sure wget is installed and get version
      shell:
        cmd: wget --version 2>&1 | head -1 | cut -d '"' -f 2
      register: wget
      check_mode: false
      changed_when: false
      failed_when: "'not found' in wget.stdout"

    - name: Audit log output for what FQDN hosts is being custom sshd harden
      ansible.builtin.debug:
        msg: "This is host/server: {{ ansible_hostname }}"

    - name: Download custom harden sshd_config file
      shell: |
        mv -n /etc/ssh/sshd_config /etc/ssh/sshd_config.{{bak_ts}}.bak 2>/dev/null || true
        mv -n /etc/ssh/sshd_public_banner.txt /etc/ssh/sshd_public_banner.txt.{{bak_ts}}.bak 2>/dev/null || true
        wget --quiet --no-passive-ftp --output-document="/etc/ssh/sshd_config" "https://gist.githubusercontent.com/kawaiipantsu/b27d953de9793731b60b4636bad7a3dc/raw/9858288accbb73e11847efcb883e571864ad3e4a/sshd_config" 2>/dev/null
        wget --quiet --no-passive-ftp --output-document="/etc/ssh/sshd_public_banner.txt" "https://gist.githubusercontent.com/kawaiipantsu/b27d953de9793731b60b4636bad7a3dc/raw/9858288accbb73e11847efcb883e571864ad3e4a/sshd_public_banner.txt" 2>/dev/null
        chmod 644 /etc/ssh/sshd_config
        chmod 644 /etc/ssh/sshd_public_banner.txt
        sha1sum /etc/ssh/sshd_config
      warn: false
      check_mode: false
      changed_when: true

    - name: restart sshd
      ansible.builtin.systemd:
        name: sshd
        state: restarted
