#   _  __                   _ _ ____             _             
#  | |/ /__ ___      ____ _(_|_)  _ \ __ _ _ __ | |_ ___ _   _ 
#  | ' // _` \ \ /\ / / _` | | | |_) / _` | '_ \| __/ __| | | |
#  | . \ (_| |\ V  V / (_| | | |  __/ (_| | | | | |_\__ \ |_| |
#  |_|\_\__,_| \_/\_/ \__,_|_|_|_|   \__,_|_| |_|\__|___/\__,_|
#                   ____  _             _                 _        
#  [   ANSIBLE   ] |  _ \| | __ _ _   _| |__   ___   ___ | | _____ 
#  Please only use | |_) | |/ _` | | | | '_ \ / _ \ / _ \| |/ / __|
#  playbooks if    |  __/| | (_| | |_| | |_) | (_) | (_) |   <\__ \
#  you know what   |_|   |_|\__,_|\__, |_.__/ \___/ \___/|_|\_\___/
#  they change/do                 |___/ 
# 
#  .---------| Debian do Localization
#  |
#  | This playbook will do the following:
#  | - Set default Locales
#  | - Update Locales with prefered avaiable
#  | - Update Locales Generated
#  | - Set Timezone and update system
#  | - Restart Contab daemon if needed
#  `---------------------------------------------------------------
---

- hosts: debian
  gather_facts: false
  tasks:
  - name: Select default locale
    debconf:
      name: locales
      question: locales/default_environment_locale
      value: en_DK.UTF-8
      vtype: select
    notify:
      - Rebuild locales database

  - name: Update /etc/locale.gen
    lineinfile:
      dest: /etc/locale.gen
      regexp: "{{ item.regexp }}"
      line: "{{ item.line }}"
      state: "{{ item.state }}"
    with_items:
      - { regexp: '^#? ?da_DK ISO-8859-1', line: 'da_DK ISO-8859-1', state: present }
      - { regexp: '^#? ?da_DK.UTF-8 UTF-8', line: 'da_DK.UTF-8 UTF-8', state: present }
      - { regexp: '^#? ?en_DK.UTF-8 UTF-8', line: 'en_DK.UTF-8 UTF-8', state: present }
      - { regexp: '^#? ?en_US ISO-8859-1', line: 'en_US ISO-8859-1', state: present }
      - { regexp: '^#? ?en_US.ISO-8859-15 ISO-8859-15', line: 'en_US.ISO-8859-15 ISO-8859-15', state: present }
      - { regexp: '^#? ?en_US.UTF-8 UTF-8', line: 'en_US.UTF-8 UTF-8', state: present }
    notify:
      - Rebuild locales database

  - name: Set timezone to Europe/Copenhagen
    community.general.timezone:
      name: Europe/Copenhagen
    register: timezone

  - name: Reconfigure timezone data (if changed)
    shell: dpkg-reconfigure -f noninteractive tzdata
    when: timezone.changed

  - name: Crontab daemon restart (if timezone changed)
    ansible.builtin.service:
      name: crond
      state: restarted
      enabled: true
    when: timezone.changed
    ignore_errors: true

  handlers:
    - name: Rebuild locales database
      command: "{{ item }}"
      with_items:
        - dpkg-reconfigure locales -f noninteractive
        - /usr/sbin/locale-gen

