#   _  __                   _ _ ____             _             
#  | |/ /__ ___      ____ _(_|_)  _ \ __ _ _ __ | |_ ___ _   _ 
#  | ' // _` \ \ /\ / / _` | | | |_) / _` | '_ \| __/ __| | | |
#  | . \ (_| |\ V  V / (_| | | |  __/ (_| | | | | |_\__ \ |_| |
#  |_|\_\__,_| \_/\_/ \__,_|_|_|_|   \__,_|_| |_|\__|___/\__,_|
#                   ____  _             _                 _        
#  [   ANSIBLE   ] |  _ \| | __ _ _   _| |__   ___   ___ | | _____ 
#  Please only use | |_) | |/ _` | | | | '_ \ / _ \ / _ \| |/ / __|
#  playbooks if    |  __/| | (_| | |_| | |_) | (_) | (_) |   <\__ \
#  you know what   |_|   |_|\__,_|\__, |_.__/ \___/ \___/|_|\_\___/
#  they change/do                 |___/ 
# 
#  .---------| My Compliance Playbooks - NTP (time sync)
#  | 
#  | This playbook will do the following:
#  | - Install NTP package to latest
#  | - Copy over the ntp.conf template
#  | - Will use your default gateway IP as default NTP server!
#  `---------------------------------------------------------------
---

- hosts: all
  tasks:
    - name: Install NTP package
      register: updatesys
      apt:
        update_cache: yes
        force_apt_get: yes
        cache_valid_time: 3600
        name:
          - ntp
        state: latest

    - name: Generate NTP configuration file.
      template:
        src: "ntp.conf.j2"
        dest: "/etc/ntp.conf"
        mode: 0644
      notify:
        - Restart NTP
        - Restart CRON

    - name: Ensure NTP is running and enabled as configured.
      service:
        name: "ntp"
        state: started
        enabled: true

  handlers:
    - name: Restart NTP
      service:
        name: "ntp"
        state: restarted
      ignore_errors: true

    - name: Restart CRON
      service:
        name: "crond"
        state: restarted
      ignore_errors: true

