#   _  __                   _ _ ____             _             
#  | |/ /__ ___      ____ _(_|_)  _ \ __ _ _ __ | |_ ___ _   _ 
#  | ' // _` \ \ /\ / / _` | | | |_) / _` | '_ \| __/ __| | | |
#  | . \ (_| |\ V  V / (_| | | |  __/ (_| | | | | |_\__ \ |_| |
#  |_|\_\__,_| \_/\_/ \__,_|_|_|_|   \__,_|_| |_|\__|___/\__,_|
#                   ____  _             _                 _        
#  [   ANSIBLE   ] |  _ \| | __ _ _   _| |__   ___   ___ | | _____ 
#  Please only use | |_) | |/ _` | | | | '_ \ / _ \ / _ \| |/ / __|
#  playbooks if    |  __/| | (_| | |_| | |_) | (_) | (_) |   <\__ \
#  you know what   |_|   |_|\__,_|\__, |_.__/ \___/ \___/|_|\_\___/
#  they change/do                 |___/ 
# 
#  .---------| My Compliance Playbooks - NTP (time sync)
#  | 
#  | This playbook will do the following:
#  | - Install NTP package to latest
#  | - Copy over the ntp.conf template
#  | - Will use your default gateway IP as default NTP server!
#  `---------------------------------------------------------------
---

- hosts: debian
  tasks:
    - name: Install ClamAV package
      register: updatesys
      apt:
        update_cache: yes
        force_apt_get: yes
        cache_valid_time: 3600
        name:
          - clamav
          - clamav-daemon
          - clamav-freshclam
        state: latest

    - name: Generate Freshclam configuration file.
      template:
        src: "freshclam.conf.j2"
        dest: "/etc/clamav/freshclam.conf"
        mode: 0644
      notify:
        - Restart CLAMAV
        
    - name: Delete stale freshclam.dat file to reuse new mirror setting
      file:
        path: /var/lib/clamav/freshclam.dat
        state: absent

    - name: Ensure ClamAV Freshclam is running and enabled as configured.
      service:
        name: "clamav-freshclam"
        state: started
        enabled: true

  handlers:
    - name: Restart CLAMAV
      service:
        name: "clamav-freshclam"
        state: restarted
      ignore_errors: true

