#   _  __                   _ _ ____             _             
#  | |/ /__ ___      ____ _(_|_)  _ \ __ _ _ __ | |_ ___ _   _ 
#  | ' // _` \ \ /\ / / _` | | | |_) / _` | '_ \| __/ __| | | |
#  | . \ (_| |\ V  V / (_| | | |  __/ (_| | | | | |_\__ \ |_| |
#  |_|\_\__,_| \_/\_/ \__,_|_|_|_|   \__,_|_| |_|\__|___/\__,_|
#                   ____  _             _                 _        
#  [   ANSIBLE   ] |  _ \| | __ _ _   _| |__   ___   ___ | | _____ 
#  Please only use | |_) | |/ _` | | | | '_ \ / _ \ / _ \| |/ / __|
#  playbooks if    |  __/| | (_| | |_| | |_) | (_) | (_) |   <\__ \
#  you know what   |_|   |_|\__,_|\__, |_.__/ \___/ \___/|_|\_\___/
#  they change/do                 |___/ 
# 
#  .---------| Debian APT Housecleaning
#  |
#  | This playbook will do the following:
#  | - Update apt cache
#  | - Semi cleanup cache
#  | - Remove package dependencies not used on the system anymore
#  | - Lastly do a full cleanup, removing the cache
#  `---------------------------------------------------------------
---

- hosts: all
  tasks:
    - name: First update apt cache for fresh dependency overview
      ansible.builtin.apt:
        update_cache: yes

    - name: Remove any unused/useless packages from the cache
      ansible.builtin.apt:
        autoclean: yes

    - name: Remove dependencies that are no longer required
      ansible.builtin.apt:
        autoremove: yes
    
    - name: Remove apt cache to free up disk space
      ansible.builtin.apt:
        clean: yes
