#   _  __                   _ _ ____             _             
#  | |/ /__ ___      ____ _(_|_)  _ \ __ _ _ __ | |_ ___ _   _ 
#  | ' // _` \ \ /\ / / _` | | | |_) / _` | '_ \| __/ __| | | |
#  | . \ (_| |\ V  V / (_| | | |  __/ (_| | | | | |_\__ \ |_| |
#  |_|\_\__,_| \_/\_/ \__,_|_|_|_|   \__,_|_| |_|\__|___/\__,_|
#                   ____  _             _                 _        
#  [   ANSIBLE   ] |  _ \| | __ _ _   _| |__   ___   ___ | | _____ 
#  Please only use | |_) | |/ _` | | | | '_ \ / _ \ / _ \| |/ / __|
#  playbooks if    |  __/| | (_| | |_| | |_) | (_) | (_) |   <\__ \
#  you know what   |_|   |_|\__,_|\__, |_.__/ \___/ \___/|_|\_\___/
#  they change/do                 |___/ 
# 
#  .---------| My "default packages" that is install on any lxc/vm
#  |
#  | This playbook will do the following:
#  | - Update apt cache
#  | - Do apt-get install (package list)
#  | - If propper VM (not LxC) also install QEMU Guest Agent
#  `---------------------------------------------------------------
---

- hosts: debian
  tasks:
    - name: Check if platform is Virtual
      lineinfile:
        dest: /sys/devices/virtual/dmi/id/sys_vendor
        line: "QEMU"
      check_mode: yes
      register: virtual
      failed_when: (virtual is changed) or (virtual is failed)
      ignore_errors: true

    - name: Check if platform is Physical
      set_fact:
        physical: true
        virtual: false
      when: virtual is changed

    - name: Set fact for Virtual
      set_fact:
        physical: false
        virtual: true
      when: virtual

    - name: Install default packages for all my lxc/vm hosts
      register: updatesys
      apt:
        update_cache: yes
        force_apt_get: yes
        cache_valid_time: 3600
        name:
          - lsb-release
          - aptitude
          - debian-goodies
          - nano
          - vim
          - wget
          - curl
          - w3m
          - ftp
          - net-tools
          - netcat-traditional
          - tcpdump
          - tshark
          - zsh
          - ca-certificates
          - cowsay
          - figlet
          - neofetch
          - htop
          - bpytop
          - mc
          - jq
        state: latest

    - name: Install QEMU Guest Agent on propper VM's
      register: updatesys
      apt:
        update_cache: yes
        force_apt_get: yes
        cache_valid_time: 3600
        name:
          - qemu-guest-agent
        state: latest
      when: virtual
